import type { Metadata } from "next";
import Navbar from "@/components/common/layout/navbar";
import Container from "@/components/common/Container";

export const metadata: Metadata = {
  title: "Hestia Warden",
  description: "Generated by create next app",
};

export default function WardenLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <div className="flex flex-col min-h-screen relative">
        <Navbar />
        <Container>{children}</Container>
      </div>
    );
}
