export const Our_service =
  "1.1 Eligibility: You must be at least 18 years old and have the legal capacity to enter into contracts in order to use our services. By using our services, you represent and warrant that you meet these eligibility requirements.1.2 Account Registration: In order to access certain features of our website or services, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.1.3 Prohibited Activities: You agree not to engage in any of the following prohibited activities:- Violating any applicable laws or regulations.- Using our website or services for any unlawful or unauthorized purpose.- Impersonating any person or entity, or falsely stating or misrepresenting your affiliation with a person or entity.- Interfering with or disrupting the operation of our website or services.";
export const Property =
  "2.1 Property Listings: If you list a property on our website, you are solely responsible for the accuracy and completeness of the information provided in the listing. You agree not to list any properties that violate any applicable laws or regulations, or that infringe upon the rights of any third party.2.2 Booking and Reservations: If you make a booking or reservation through our website, you agree to comply with the terms and conditions set forth by the property owner or manager, including any cancellation policies and house rules.";
export const Payment =
  " 3.1 Payment: You agree to pay all fees and charges associated with your use of our website or services, including booking fees, transaction fees, and any applicable taxes.3.2 Refunds: Refunds for bookings are subject to the cancellation policies set forth by the property owner or manager. We are not responsible for issuing refunds for bookings cancelled by you or the property owner.";
export const Intellectual =
  "4.1 Ownership: All content and materials available on our website or services, including text, graphics, logos, images, and software, are the property of [Your Company Name] or its licensors and are protected by copyright, trademark, and other intellectual property laws.4.2 License: We grant you a limited, non-exclusive, non-transferable license to access and use our website and services for your personal and non-commercial use.";
export const Indemnification =
  "7.1 Indemnity: You agree to indemnify and hold harmless [Your Company Name], its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including legal fees, arising out of or in connection with your use of our website or services, your violation of these Terms, or your violation of any rights of any third party.";
export const Governing =
  "8.1 Governing Law: These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law principles.8.2 Dispute Resolution: Any dispute, controversy, or claim arising out of or in connection with these Terms shall be resolved through arbitration administered by [Arbitration Organization] in accordance with its rules and procedures.";
