export const Date =
  " Hestia is committed to protecting the privacy and security of your personal information. This Privacy Policy explains how we collect, use, and disclose information when you use our website or services. By accessing or using our website or services, you agree to the terms of this Privacy Policy.";
export const Information =
  " Personal Information: When you create an account or use our services, we may collect personal information such as your name, email address, phone number, and payment information. Property Information: If you list a property on our website, we may collect information about the property, including its location, features, and availability.Booking and Transaction Information: When you make a booking or transaction through our website, we collect information such as the dates of your stay, payment details, and communication with the property owner.Usage Information: We may collect information about how you interact with our website, such as your browsing activities, search queries, and preferences.Device Information: We may collect information about the device you use to access our website, such as your IP address, browser type, and operating system.";
export const How_Use =
  "We use the information we collect for the following purposes:1. Providing and Improving Our Services: To provide and maintain our website and services, personalize your experience, and improve the quality of our services.2. Communicating with You: To communicate with you about your account, bookings, and transactions, as well as to respond to your inquiries and provide customer support.3. Marketing and Advertising: To send you promotional materials, offers, and updates about our products and services, unless you opt out of receiving such communications.4. Analytics and Research: To analyze trends, track user activities, and conduct research to improve our website and services.";
export const Information_Sharing =
  "We may share your information with the following parties: 1. Property Owners: If you make a booking or transaction through our website, we may share your information with the property owner or manager for the purpose of fulfilling your booking.2. Service Providers: We may engage third-party service providers to assist us in providing and maintaining our website and services, including hosting, payment processing, and analytics.3. Legal Compliance: We may disclose your information if required by law or legal process, or if we believe that such disclosure is necessary to protect our rights, property, or safety, or the rights, property, or safety of others.";
export const data =
  "We take reasonable measures to protect the security of your personal information and prevent unauthorized access, use, or disclosure. However, no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.";
export const children_policy =
  "Our website and services are not intended for children under the age of 13, and we do not knowingly collect personal information from children under the age of 13. If you believe that we have collected personal information from a child under the age of 13, please contact us immediately.";
